### ISSUE TITLE
modifying /etc/erlinit.config

### ISSUE THREAD

**Issue by mikegogulski** [nerves-project/nerves-examples#21]
Putting this here since it's the repo closest to what I've been doing in, e.g., developing this PR: https://github.com/nerves-project/nerves_system_qemu_arm/pull/3

I'm aiming to soon run dozens of nerves instances under QEMU on a single machine, and the way that works right now one ends up with dozens of SDL windows displaying the console framebuffer. When nerves starts up, it mentions that the elixir shell can be started on a different tty (ttyAMA0 vs tty1), which would allow me to add something like -nographic to my QEMU command to dispose of the framebuffers entirely.

It would be nice if in these example projects (which l imagine eventually become part of a system development kit) we could do things like alter or overlay the /etc/erlinit.conf that gets baked into the firmware image. The `rootfs-additions` capability doesn't reach down to here yet.

Seems-Related: https://github.com/nerves-project/nerves/issues/25

**Comment by fhunleth** [comment]
I think that everything supports what you need, but it's not document well. Let me say a whole bunch of things and see what you think.

First, the rootfs-additions feature would work fine in the examples currently, but we don't use it. All that would need to be done would be to add it to the `config.exs` and the rootfs-addition directory for each example.

However, while the examples could supply a rootfs-additions directory, it would be hard to maintain. For example, if we override `erlinit.config` in the example, we'd have to reference the right erlinit.config for the each target since each target has a different preferred console (and a couple other minor differences). That will need to be kept in sync with each system image. 

Also, if I'm understanding this issue correctly, you want the Elixir shell on ttyAMA0, right? Except for the recent change in nerves_system_qemu_arm to point it to tty1, the erlinit.config in nerves_system_qemu_arm will propagate to the examples on the next official build. Until then, anyone wanting to use the latest nerves_system_qemu_arm can point to the ci produced build by referencing the github ref in their mix.exs.

For the last point, we should decide what is the most common case for qemu users (ttyAMA0 or tty1) and change the `nerves_system_qemu_arm/rootfs-additions/etc/erlinit.config` to do that. Anyone who doesn't like it can override `erlinit.config` in their project. The Nerves examples will be the default way, though.

**Comment by mikegogulski** [comment]
(fyi: @bendiken and I are tag-teaming this stuff, so responses might come from either of us)

**Comment by GregMefford** [comment]
Updated [QEMU System v.0.6.1](https://github.com/nerves-project/nerves_system_qemu_arm/releases/tag/v0.6.1) has been released with the terminal set to the serial port.

**Comment by fhunleth** [comment]
I think that we can close this now.

**Comment by bendiken** [comment]
Yes, good to close. I'll go ahead and update the README instructions and screenshots in the qemu_arm repository to reflect the tty change now that the change has been released.

**Comment by fhunleth** [comment]
Thanks!
