### ISSUE TITLE
neopixel doesnt address 1 pixel per 4 pixel device tested on 7,8,12 neopixel

### ISSUE THREAD

**Issue by mgnshawn** [nerves-project/nerves-examples#36]
I just received new 7,8,12 pixel neopixels and a new RPI3.  After building the neopixel example fresh with updated packages I found that whether I use `Nerves.Neopixel.render` or `Nerves.Neopixel.Animate.pulse` or `Nerves.Neopixel.Animate.spinner`, it doesn't address (devicePixels/4). The un-activated pixels are in a row and judging by the position of the IN_wire on the 8stick and 12ring I suspect they're the highest addresses in the chain.

my `config.exs` is:
`config :neopixel, :channel0, pin:18, count:12`  or 7,8 depending on the device attached.

The example also doesn't work for me when I try to use the example's workers I have to trigger via Iex but that's an issue after the fact and probably on me.

**Comment by GregMefford** [comment]
After a lot of troubleshooting, we were able to determine that the issue was with grounding between the Raspberry Pi and the NeoPixel strip. I'll work on releasing an updated version of the `nerves_neopixel` library that explicitly supports RGBW devices as opposed to just the older RGB devices.

I think as far as this issue on the `nerves-examples` project is concerned, we can close it because it turned out to be a hardware problem.
