### ISSUE TITLE
Add character LCD example.

### ISSUE THREAD

**Issue by LTheGreats** [nerves-project/nerves-examples#43]
I believe that there should be a character LCD example using the library ex_lcd.

**Comment by fhunleth** [comment]
While we don't have a hard and fast rule for what's included in nerves-examples, this seems like something that would be hard for the core team to maintain right now. I think that your example project is pretty easy to find.

**Comment by GregMefford** [comment]
The [`ex_lcd`](https://hex.pm/packages/ex_lcd) library has been added to the [list of community-supported libraries on nerves-project.org](http://nerves-project.org/libraries/) as well.

Having recently spent a lot of time bringing our existing `nerves-examples` repo current with Nerves 0.5, I agree that we shouldn't go too crazy with example projects for everything we can think of. On the other hand, I agree that it's important to have some kind of guide for how to do things beyond the simple examples we have. My vision was to have lots of guides about how to interface with different types of hardware in our [Nerves documentation](https://github.com/nerves-project/nerves/tree/master/docs), but I haven't taken the time to flesh that out yet.

In the case of `ex_lcd`, maybe the best course of action for now would be in the form of contributing to the `README` or Wiki on that repository. We can continue to discuss what we want to do about detailed guides in the docs, but it's always helpful to have good how-to docs along with the project repository itself, so it makes sense to contribute there first.

**Comment by GregMefford** [comment]
I'm going to go ahead and close this issue because I think that this repository should be limited to demonstrating core Nerves features, whereas LCDs would be handled by one of a number of Nerves-friendly libraries, not by Nerves itself.

I think the best place for this type of example would be in the library that implements the functionality, so that the library's maintainer would be responsible for keeping it current, rather than the Nerves core team having to keep up with examples that use many different libraries.
